ollama_model: "llama3.2:3b"
with_date: true
prompt:
  main: "Summarise the content between START_HERE and END_HERE in English to less than 70 characters, including the main creator of the document. Respond with ONLY the unquoted summary. ONLY THE GENERATED SUMMARY WITH NO QUOTES. If you are unable to summarise the content, respond with NO TITLE GENERATED."
  with_date: ""
  no_date: ""
  pre_content: "START_HERE "
  post_content: " END_HERE"

